-- SentinelMesh-AI Supabase setup
-- Run this file in Supabase SQL Editor for project: SentinelMesh-AI

create table if not exists public.incidents (
  id bigint generated always as identity primary key,
  created_at timestamp with time zone not null default now(),
  classification text,
  confidence integer,
  threat text,
  alert_level integer,
  path text,
  duration_sec double precision,
  avg_move_time double precision,
  node_count integer,
  pir_count integer,
  vib_count integer,
  min_distance double precision,

  constraint incidents_confidence_range
    check (confidence is null or confidence between 0 and 100),
  constraint incidents_alert_level_range
    check (alert_level is null or alert_level between 0 and 5),
  constraint incidents_classification_known
    check (
      classification is null
      or upper(classification) in ('HUMAN', 'ANIMAL', 'VEHICLE', 'UNKNOWN')
    ),
  constraint incidents_threat_known
    check (
      threat is null
      or upper(threat) in ('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
    )
);

comment on table public.incidents is
  'SentinelMesh-AI incident records received from MQTT topic perimeter/incident.';

comment on column public.incidents.created_at is
  'Cloud persistence timestamp generated by Supabase when the incident row is inserted.';

-- Fast lookups for dashboard analytics and historical search.
create index if not exists incidents_created_at_idx
  on public.incidents (created_at desc);

create index if not exists incidents_classification_idx
  on public.incidents (upper(classification));

create index if not exists incidents_threat_idx
  on public.incidents (upper(threat));

create index if not exists incidents_alert_level_idx
  on public.incidents (alert_level);

-- Keep direct browser access locked down. Flask should insert using the
-- Supabase service-role key stored on the server, never in frontend code.
alter table public.incidents enable row level security;

-- KPI cards: total incidents, classification counts, and critical alerts.
create or replace view public.incident_kpis as
select
  count(*)::integer as total_incidents,
  count(*) filter (where upper(classification) = 'HUMAN')::integer as humans,
  count(*) filter (where upper(classification) = 'ANIMAL')::integer as animals,
  count(*) filter (where upper(classification) = 'VEHICLE')::integer as vehicles,
  count(*) filter (
    where upper(threat) = 'CRITICAL' or alert_level >= 3
  )::integer as critical_alerts
from public.incidents;

-- Chart: threat distribution.
create or replace view public.threat_distribution as
select
  coalesce(upper(threat), 'UNKNOWN') as threat,
  count(*)::integer as incident_count
from public.incidents
group by coalesce(upper(threat), 'UNKNOWN')
order by incident_count desc, threat;

-- Chart: classification distribution.
create or replace view public.classification_distribution as
select
  coalesce(upper(classification), 'UNKNOWN') as classification,
  count(*)::integer as incident_count
from public.incidents
group by coalesce(upper(classification), 'UNKNOWN')
order by incident_count desc, classification;

-- Chart: node activity. Supports paths like:
-- SOUTH -> WEST -> NORTH, SOUTH/WEST/NORTH with arrow separators,
-- or SOUTH,WEST,NORTH.
create or replace view public.node_activity as
select
  upper(trim(node_name)) as node,
  count(*)::integer as incident_count
from public.incidents i
cross join lateral regexp_split_to_table(
  coalesce(i.path, ''),
  '\s*(?:->|' || chr(8594) || '|,)\s*'
) as node_name
where trim(node_name) <> ''
group by upper(trim(node_name))
order by incident_count desc, node;

-- Chart: incidents per hour.
create or replace view public.incidents_per_hour as
select
  date_trunc('hour', created_at) as hour_bucket,
  count(*)::integer as incident_count
from public.incidents
group by date_trunc('hour', created_at)
order by hour_bucket desc;

-- Useful historical demo queries:
-- All critical incidents:
-- select * from public.incidents
-- where upper(threat) = 'CRITICAL' or alert_level >= 3
-- order by created_at desc;
--
-- Last 24 hours:
-- select * from public.incidents
-- where created_at >= now() - interval '24 hours'
-- order by created_at desc;
--
-- Vehicle detections:
-- select * from public.incidents
-- where upper(classification) = 'VEHICLE'
-- order by created_at desc;
